xcodeproj 'ING.Assignment.xcodeproj'

    use_frameworks!


target 'ING.Assignment' do



pod 'XKPhotoScrollView'
pod 'Sheriff', :git => 'https://github.com/gemr/Sheriff.git'
pod 'AlamofireImage', '~> 3.1'
pod 'Fontello-Swift/Entypo'
pod 'Fontello-Swift/ModernPictograms'

pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'RxAlamofire'


target 'ING.Assignment.TodayWidget' do
    inherit! :search_paths
    pod 'Alamofire'
    pod 'PromiseKit'
    pod 'OHHTTPStubs'
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'RxAlamofire'
end


end


target 'ING.AssignmentTests' do
    pod 'Alamofire'
    pod 'AlamofireImage', '~> 3.1'
    pod 'PromiseKit'
    pod 'OHHTTPStubs'
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'RxAlamofire'
end

target 'ING.Assignment.Watch Extension' do
    platform :watchos, ‘2.0’

use_frameworks!

pod 'Alamofire'
pod 'AlamofireImage', '~> 3.1'
pod 'PromiseKit'
pod 'OHHTTPStubs'

pod 'RxSwift'
pod 'RxCocoa'
pod 'RxAlamofire'

end


